baseURL = "https://geekandlatin.com"
languageCode = "en-us"
title = "Geek and Latin"
theme = "anubis"
paginate = 5

disqusShortname = "sudarshan-reddy.github.io"
googleAnalytics = ""

[author]
  name = "Sudarshan"

[params]
   author = "Sudarshan Reddy"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    name = "resume"
    identifier = "resume"
    url = "/resume/"
    weight = 3

[taxonomies]
category = "categories"
tag = "tags"
